name: Mi primer workflow manual

on:
  workflow_dispatch:
    inputs:
      mensaje:
        description: 'Escribe un mensaje para mostrar'
        required: false

jobs:
  mostrar-mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar el mensaje que escribiste
        run: echo "Tu mensaje fue: ${{ github.event.inputs.mensaje }}"
