name: Testear YAML sin errores

on:
  workflow_dispatch:
    inputs:
      mensaje:
        description: 'Escribe un mensaje para mostrar'
        required: false
        default: '¡Hola, este es un test sin errores!'

jobs:
  mostrar-mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar el mensaje
        run: echo "Tu mensaje fue: ${{ github.event.inputs.mensaje }}"
